export const projects = [
  { id: 1, name: 'Nebula Design System', desc: 'Building a unified component library for all internal products.', type: 'Design System', status: 'active', progress: 72, team: 6, deadline: 'Mar 15, 2026', skills: ['Figma', 'React', 'CSS'], color: 'purple', avatars: ['AS', 'KP', 'JM', 'RL'] },
  { id: 2, name: 'DataFlow ML Pipeline', desc: 'Machine learning pipeline for real-time resource allocation.', type: 'Data / ML', status: 'active', progress: 45, team: 4, deadline: 'Apr 2, 2026', skills: ['Python', 'TensorFlow', 'SQL'], color: 'teal', avatars: ['PR', 'DK', 'SA'] },
  { id: 3, name: 'Horizon CRM', desc: 'Customer relationship management system for enterprise sales.', type: 'Product Development', status: 'review', progress: 91, team: 8, deadline: 'Feb 28, 2026', skills: ['Node.js', 'React', 'PostgreSQL'], color: 'indigo', avatars: ['JL', 'MN', 'OT'] },
  { id: 4, name: 'Phoenix Mobile App', desc: 'Companion mobile app for SkillSync — iOS and Android.', type: 'Product Development', status: 'active', progress: 33, team: 5, deadline: 'Jun 1, 2026', skills: ['React Native', 'TypeScript'], color: 'pink', avatars: ['BW', 'CT', 'DM'] },
  { id: 5, name: 'CloudShift Infra', desc: 'Migrating legacy services to Kubernetes on AWS.', type: 'Infrastructure', status: 'plan', progress: 8, team: 3, deadline: 'Jul 30, 2026', skills: ['AWS', 'Kubernetes', 'Terraform'], color: 'amber', avatars: ['FG', 'HI'] },
  { id: 6, name: 'Atlas Analytics', desc: 'Internal analytics dashboard for C-suite reporting.', type: 'Research', status: 'hold', progress: 55, team: 2, deadline: 'May 10, 2026', skills: ['D3.js', 'BigQuery'], color: 'indigo', avatars: ['JK', 'LM'] },
];

export const employees = [
  { id: 1, name: 'Aisha Sharma', initials: 'AS', role: 'Senior Frontend Dev', dept: 'Engineering', avail: 'available', skills: ['React', 'TypeScript', 'CSS', 'Figma', 'Next.js'], coreSkill: 'React', rating: 4.9, projects: 2, completedProjs: 8, exp: '5 yrs', assignedTo: ['Nebula Design System', 'Horizon CRM'], bio: 'Expert in modern React patterns and design systems. Led 3 major redesigns.' },
  { id: 2, name: 'Rahul Mehta', initials: 'RM', role: 'ML Engineer', dept: 'Data & AI', avail: 'partial', skills: ['Python', 'TensorFlow', 'SQL', 'Scikit-learn', 'PyTorch'], coreSkill: 'Python', rating: 4.7, projects: 3, completedProjs: 5, exp: '4 yrs', assignedTo: ['DataFlow ML Pipeline'], bio: 'Specializes in real-time ML pipelines and NLP models.' },
  { id: 3, name: 'Sophie Chen', initials: 'SC', role: 'UX Designer', dept: 'Design', avail: 'available', skills: ['Figma', 'Principle', 'Framer', 'User Research', 'Prototyping'], coreSkill: 'Figma', rating: 4.8, projects: 1, completedProjs: 12, exp: '6 yrs', assignedTo: ['Nebula Design System'], bio: 'Human-centered designer with deep expertise in enterprise UX.' },
  { id: 4, name: "James O'Brien", initials: 'JO', role: 'Backend Engineer', dept: 'Engineering', avail: 'busy', skills: ['Node.js', 'PostgreSQL', 'AWS', 'Docker', 'GraphQL'], coreSkill: 'Node.js', rating: 4.6, projects: 4, completedProjs: 9, exp: '7 yrs', assignedTo: ['Horizon CRM', 'Atlas Analytics'], bio: 'Veteran backend engineer focused on scalable API architecture.' },
  { id: 5, name: 'Priya Patel', initials: 'PP', role: 'DevOps Engineer', dept: 'Infrastructure', avail: 'partial', skills: ['Kubernetes', 'Terraform', 'CI/CD', 'AWS', 'Prometheus'], coreSkill: 'Kubernetes', rating: 4.5, projects: 2, completedProjs: 6, exp: '3 yrs', assignedTo: ['CloudShift Infra'], bio: 'DevOps specialist focused on cloud-native infrastructure.' },
  { id: 6, name: 'Carlos Rivera', initials: 'CR', role: 'Data Engineer', dept: 'Data & AI', avail: 'available', skills: ['BigQuery', 'dbt', 'Python', 'Airflow', 'Spark'], coreSkill: 'BigQuery', rating: 4.9, projects: 1, completedProjs: 7, exp: '5 yrs', assignedTo: ['Atlas Analytics'], bio: 'Data pipeline architect with expertise in real-time analytics.' },
];

export const polls = [
  { id: 1, status: 'open', question: 'What is your preferred sprint length?', category: 'Sprint Planning', created: 'Feb 18, 2026', responses: 8, total: 12, options: [{ label: '1 Week', votes: 3 }, { label: '2 Weeks', votes: 4 }, { label: '3 Weeks', votes: 1 }] },
  { id: 2, status: 'open', question: 'Are you available for overtime in Q2?', category: 'Availability', created: 'Feb 19, 2026', responses: 5, total: 12, options: [{ label: 'Yes, flexible', votes: 2 }, { label: 'Limited availability', votes: 2 }, { label: 'Not available', votes: 1 }] },
  { id: 3, status: 'open', question: 'What remote work setup do you prefer?', category: 'Work Preferences', created: 'Feb 20, 2026', responses: 3, total: 12, options: [{ label: 'Fully remote', votes: 2 }, { label: 'Hybrid (2-3 days)', votes: 1 }, { label: 'In-office', votes: 0 }] },
];
