/**
 * Canonical skill list used for extraction and matching.
 * Keys are lowercase/normalised forms; values are the display names.
 */
export const SKILL_MAP: Record<string, string> = {
  // Frontend
  'react':               'React',
  'react.js':            'React',
  'reactjs':             'React',
  'next.js':             'Next.js',
  'nextjs':              'Next.js',
  'vue':                 'Vue.js',
  'vue.js':              'Vue.js',
  'vuejs':               'Vue.js',
  'angular':             'Angular',
  'svelte':              'Svelte',
  'javascript':          'JavaScript',
  'js':                  'JavaScript',
  'typescript':          'TypeScript',
  'ts':                  'TypeScript',
  'html':                'HTML',
  'html5':               'HTML',
  'css':                 'CSS',
  'css3':                'CSS',
  'tailwind':            'Tailwind CSS',
  'tailwindcss':         'Tailwind CSS',
  'tailwind css':        'Tailwind CSS',
  'sass':                'Sass',
  'scss':                'Sass',
  'bootstrap':           'Bootstrap',
  'material ui':         'Material UI',
  'mui':                 'Material UI',

  // Backend
  'node':                'Node.js',
  'node.js':             'Node.js',
  'nodejs':              'Node.js',
  'express':             'Express.js',
  'express.js':          'Express.js',
  'expressjs':           'Express.js',
  'fastapi':             'FastAPI',
  'django':              'Django',
  'flask':               'Flask',
  'spring':              'Spring Boot',
  'spring boot':         'Spring Boot',
  'laravel':             'Laravel',

  // Databases
  'mongodb':             'MongoDB',
  'mongo':               'MongoDB',
  'postgresql':          'PostgreSQL',
  'postgres':            'PostgreSQL',
  'mysql':               'MySQL',
  'sqlite':              'SQLite',
  'redis':               'Redis',
  'firebase':            'Firebase',
  'supabase':            'Supabase',
  'sql':                 'SQL',

  // Languages
  'python':              'Python',
  'java':                'Java',
  'c++':                 'C++',
  'cpp':                 'C++',
  'c#':                  'C#',
  'csharp':              'C#',
  'go':                  'Go',
  'golang':              'Go',
  'rust':                'Rust',
  'kotlin':              'Kotlin',
  'swift':               'Swift',
  'php':                 'PHP',
  'ruby':                'Ruby',
  'scala':               'Scala',
  'r':                   'R',

  // Cloud / DevOps
  'aws':                 'AWS',
  'amazon web services': 'AWS',
  'azure':               'Azure',
  'gcp':                 'GCP',
  'google cloud':        'GCP',
  'docker':              'Docker',
  'kubernetes':          'Kubernetes',
  'k8s':                 'Kubernetes',
  'terraform':           'Terraform',
  'ci/cd':               'CI/CD',
  'jenkins':             'Jenkins',
  'github actions':      'GitHub Actions',

  // Tools
  'git':                 'Git',
  'github':              'GitHub',
  'gitlab':              'GitLab',
  'rest':                'REST API',
  'rest api':            'REST API',
  'restful':             'REST API',
  'graphql':             'GraphQL',
  'websocket':           'WebSockets',
  'websockets':          'WebSockets',
  'jest':                'Jest',
  'cypress':             'Cypress',
  'figma':               'Figma',
  'linux':               'Linux',
  'bash':                'Bash',
  'shell':               'Bash',

  // AI / ML
  'machine learning':    'Machine Learning',
  'ml':                  'Machine Learning',
  'deep learning':       'Deep Learning',
  'tensorflow':          'TensorFlow',
  'pytorch':             'PyTorch',
  'pandas':              'Pandas',
  'numpy':               'NumPy',
  'scikit-learn':        'Scikit-learn',
  'sklearn':             'Scikit-learn',
  'llm':                 'LLM',
  'openai':              'OpenAI',
};

/** All canonical display names (unique values) */
export const ALL_SKILLS = [...new Set(Object.values(SKILL_MAP))].sort();
